version: "3.9"

services:
  flask:
    image: flask-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis:latest
