version: "3.9"

services:
  flask:
    image: links-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:latest
